---
- name: all
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
    - name: update apt in ubuntu
      apt:
        upgrade: true
        update_cache: true
      register: apt
    - debug: msg={{ apt.stdout.split('\n')[:-1] }}


    - name: NGINX | Install NGINX package from apt
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration


  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

